# Generated by Django 4.2.7 on 2023-12-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
